version: "3.8"

services:
  nextjs:
    build: .
    container_name: ssaagency
    restart: unless-stopped
    ports:
      - "3001:3000"
    networks:
      - nginx

networks:
  nginx:
    name: nginx_network
    external: true